debug: False
dbname: "database.db"
# Use a relative path that is easy for the workflow to find
dbpath: "database" 
server_proxy: 127.0.0.1
port_proxy: 9050
type_proxy: socks5h
timeout: 30
score_categorie: 20
score_keywords: 40
count_categories: 5
daystime: 10
# Set to False unless you have a logging listener running
sendlog: False 
logport: 5151
logip: "127.0.0.1"
